name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Deploy backend
        run: |
          mkdir -p -m 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./backend/*.py ./backend/requirements.txt ./backend/resources ./backend/auth ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/Tikkle/backend
      - name: Deploy frontend using SCP
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r ./frontend/dist/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/tikkle
      - name: Restart backend
        run: ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ~/Tikkle/backend ; source venv/bin/activate ; python3 -m pip install -r requirements.txt ; sudo systemctl restart fastapi"
