name: Test

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  test-backend:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
    env:
      AUTH_KEY: ${{ secrets.AUTH_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pytest test/

  test-frontend:
    runs-on: ubuntu-latest
    container:
      image: node:20-slim
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - name: Install dependencies
        working-directory: ./frontend
        run: |
          npm install
          npm test
          npm run build
